# ITG-Buddy configuration file
# This file is a template. Copy it to config.yaml and edit it to your needs.

# Discord bot token
token: ""

# Discord bot client ID
clientId: ""

# Discord guild ID and channel ID for drag & drop add-song
guildId: ""
addSongChannel: ""

# Discord user ID to be notified in the case of errors.
adminID: ""

# Path to itgmania itg-cli main.py file. Used to launch itg-cli.
itgCliPath: ""

# Path to itgmania Save folder. Used to watch for for gamestate updates.
# Make sure you have the ScreenSwitcher and WriteSongInfo modules installed.
# https://github.com/Simply-Love/Simply-Love-Modules
saveFolder: "" # Comment this line if you don't want to use this feature.

# Path to doorbell script. Used to notify players that someone is at the door.
# Stdout is sent to the console for debugging.
doorbellPath: ""
